version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: 'redis-server --requirepass devpassword'
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:10.3-alpine'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "vidme.app:create_app()"
    depends_on:
      - 'postgres'
    env_file:
      - '.env'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'

  celery:
    build: .
    command: 'celery worker -l info -A vidme.blueprints.admin.tasks'
    env_file:
      - '.env'
    volumes:
      - '.:/app'

volumes:
  redis:
  postgres:
